* `autograd` (automatic differentiation) is an important part of all NN in pytorch
* Backprop is defined by how the code is run, tracks operations, so every iteration can be different depending on the last operation
* Computation Graph
    - `Tensor`s are nodes
    - `Function`s are edges
* Use the `.backward()` function to calc the derivative of a tensor


In [11]:
import torch

In [12]:
# Create a tensor and begin tracking operations
x = torch.ones( 2 , 2 , requires_grad = True )
print( x )

tensor([[1., 1.],
        [1., 1.]], requires_grad=True)


In [13]:
# Do a tensor operation
y = x + 2
print( y )
print( y.grad_fn )

tensor([[3., 3.],
        [3., 3.]], grad_fn=<AddBackward0>)


In [14]:
z = y * y * 3
out = z.mean()

print( z , '\n' , out )

tensor([[27., 27.],
        [27., 27.]], grad_fn=<MulBackward0>) 
 tensor(27., grad_fn=<MeanBackward0>)


In [15]:
a = torch.randn( 2 , 2 ) #- Create a random tensor `a`
a = ( (a * 3) / (a - 1) ) # Do some math on `a`
print( a.requires_grad ) #- Does this tensor track operations? (No)
a.requires_grad_( True ) #- Set the tensor to track operations
print( a.requires_grad ) #- Does this tensor track operations? (Yes)
b = ( a * a ).sum() # ----- Define `b` in terms of `a`
print( b.grad_fn ) # ------ Gradient function for `b`

False
True


In [16]:
# Gradient of `out`
out.backward()
print( x.grad )

tensor([[4.5000, 4.5000],
        [4.5000, 4.5000]])


* `torch.autograd` is an engine for computing vector-Jacobian product

In [19]:
x = torch.randn(3, requires_grad=True)

y = x * 2
while y.data.norm() < 1000:
    y = y * 2

print( y )

v = torch.tensor( [0.1, 1.0, 0.0001], dtype=torch.float )
y.backward( v )

print( x.grad )

tensor([  622.4786,   186.5931, -1040.9867], grad_fn=<MulBackward0>)
tensor([1.0240e+02, 1.0240e+03, 1.0240e-01])


In [21]:
print(x.requires_grad)
print((x ** 2).requires_grad)

with torch.no_grad(): # Disable ops tracking for the block
    print((x ** 2).requires_grad)

True
True
False


In [22]:
print(x.requires_grad)
y = x.detach()
print(y.requires_grad)
print(x.eq(y).all())

True
False
tensor(True)
