In [1]:
import torch

In [2]:
x = torch.empty( 5 , 3 ) # Create an array filled with garbage data
print( x )

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])


In [3]:
x = torch.rand( 5 , 3 ) # Create an array filled with random data on [0,1]
print( x )

tensor([[0.9617, 0.1636, 0.6546],
        [0.5001, 0.3040, 0.5008],
        [0.8085, 0.8160, 0.4817],
        [0.3363, 0.6400, 0.4595],
        [0.7180, 0.7703, 0.8465]])


In [4]:
x = torch.tensor( [ 5.5 , 3 ] ) # Construct a tensor directly from data
print( x )

tensor([5.5000, 3.0000])


In [5]:
x = x.new_ones( 5 , 3 , dtype=torch.double )      # new_* methods take in sizes
print( x )

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)


In [6]:
x = torch.randn_like(x, dtype=torch.float)    # override dtype!
print(x)                                      # result has the same size

tensor([[ 0.8661, -0.0315, -0.1620],
        [-0.4901,  0.2630, -1.9492],
        [ 0.8513, -1.2547, -0.1333],
        [-0.0410, -0.7678, -0.6046],
        [ 0.7059, -0.6628,  0.4992]])


In [7]:
print(x.size())

torch.Size([5, 3])


In [8]:
x = torch.randn_like(x, dtype=torch.float)    # override dtype!
y = torch.rand(5, 3)

print(x + y)

print(torch.add(x, y))

result = torch.empty(5, 3)
torch.add(x, y, out=result)
print(result)

tensor([[-1.5978,  0.7147, -1.9290],
        [ 2.3372,  1.1124, -0.6444],
        [ 0.7259,  1.1458,  0.9129],
        [ 0.6933,  0.2520, -0.1537],
        [ 0.6919, -0.8428, -1.1119]])
tensor([[-1.5978,  0.7147, -1.9290],
        [ 2.3372,  1.1124, -0.6444],
        [ 0.7259,  1.1458,  0.9129],
        [ 0.6933,  0.2520, -0.1537],
        [ 0.6919, -0.8428, -1.1119]])
tensor([[-1.5978,  0.7147, -1.9290],
        [ 2.3372,  1.1124, -0.6444],
        [ 0.7259,  1.1458,  0.9129],
        [ 0.6933,  0.2520, -0.1537],
        [ 0.6919, -0.8428, -1.1119]])


In [9]:
# adds x to y
y.add_(x) # Any operation that mutates a tensor in-place is post-fixed with an _. For example: x.copy_(y), x.t_(), will change x
print(y)

tensor([[-1.5978,  0.7147, -1.9290],
        [ 2.3372,  1.1124, -0.6444],
        [ 0.7259,  1.1458,  0.9129],
        [ 0.6933,  0.2520, -0.1537],
        [ 0.6919, -0.8428, -1.1119]])


In [10]:
x = torch.randn(4, 4)
y = x.view(16)
z = x.view(-1, 8)  # the size -1 is inferred from other dimensions
print(x.size(), y.size(), z.size())

torch.Size([4, 4]) torch.Size([16]) torch.Size([2, 8])


In [11]:
x = torch.randn(1) # If you have a one element tensor, use .item() to get the value as a Python number
print(x)
print(x.item())

tensor([-1.3352])
-1.3352196216583252


In [12]:
a = torch.ones(5)
print(a)
b = a.numpy()
print(b)

tensor([1., 1., 1., 1., 1.])
[1. 1. 1. 1. 1.]


In [13]:
a.add_(1)
print(a)
print(b) # b is changed automatically!

tensor([2., 2., 2., 2., 2.])
[2. 2. 2. 2. 2.]


In [14]:
import numpy as np
a = np.ones(5)
b = torch.from_numpy(a)
np.add(a, 1, out=a)
print(a)
print(b) # `b` was changed automatically

[2. 2. 2. 2. 2.]
tensor([2., 2., 2., 2., 2.], dtype=torch.float64)


In [1]:
import torch

x = torch.randn(4, 4)
x = torch.randn_like(x, dtype=torch.float)    # override dtype!
y = torch.rand(5, 3)

# let us run this cell only if CUDA is available
# We will use ``torch.device`` objects to move tensors in and out of GPU
if torch.cuda.is_available():
    device = torch.device("cuda")          # a CUDA device object
    y = torch.ones_like(x, device=device)  # directly create a tensor on GPU
    x = x.to(device)                       # or just use strings ``.to("cuda")``
    z = x + y
    print(z)
    print(z.to("cpu", torch.double))       # ``.to`` can also change dtype together!
else:
    print( "CUDA was NOT available!" )

/usr/local/lib/python3.6/dist-packages/torch/cuda/__init__.py:82: UserWarning: 
    Found GPU0 GeForce GTX 650 which is of cuda capability 3.0.
    PyTorch no longer supports this GPU because it is too old.
    The minimum cuda capability that we support is 3.5.
    
  warnings.warn(old_gpu_warn % (d, name, major, capability[1]))


tensor([[ 0.1565, -1.4642,  2.9285,  0.2117],
        [ 1.4248,  0.0816,  1.9106,  2.6143],
        [ 1.3546, -0.1743,  1.4176,  1.8343],
        [-0.4066,  1.4714,  1.0181,  1.3366]], device='cuda:0')
tensor([[ 0.1565, -1.4642,  2.9285,  0.2117],
        [ 1.4248,  0.0816,  1.9106,  2.6143],
        [ 1.3546, -0.1743,  1.4176,  1.8343],
        [-0.4066,  1.4714,  1.0181,  1.3366]], dtype=torch.float64)
